REFRESH MATERIALIZED VIEW CONCURRENTLY report.users;
ANALYSE report.users;

REFRESH MATERIALIZED VIEW CONCURRENTLY report.user_map;
ANALYSE report.user_map;

REFRESH MATERIALIZED VIEW CONCURRENTLY report.users_sensitive;
ANALYSE report.users_sensitive;

REFRESH MATERIALIZED VIEW CONCURRENTLY report.group_map;
ANALYSE report.group_map;

REFRESH MATERIALIZED VIEW CONCURRENTLY report.groups;
ANALYSE report.groups;

REFRESH MATERIALIZED VIEW CONCURRENTLY report.events;
ANALYSE report.events;
