groups:
  babel:
    patterns:
      - '@babel/*'
  eslint:
    patterns:
      - 'eslint*'
      - 'typescript-eslint'
  rollup:
    patterns:
      - 'rollup'
      - '@rollup/*'
  sentry:
    patterns:
      - '@sentry/*'
  typescript-types:
    patterns:
      - '@types/*'
  vitest:
    patterns:
      - 'vitest'
      - '@vitest/*'
