from datetime import timedelta
from typing import Callable
from urllib.parse import parse_qs, urlparse

from lms.models import EmailUnsubscribe
from lms.services.exceptions import ExpiredJWTError, InvalidJWTError
from lms.services.jwt import JWTService
from lms.services.upsert import bulk_upsert


class UnrecognisedURLError(Exception):
    pass


class InvalidTokenError(Exception):
    pass


class EmailPreferencesService:
    def __init__(self, db, jwt_service: JWTService, secret: str, route_url: Callable):
        self._db = db
        self._jwt_service = jwt_service
        self._secret = secret
        self._route_url = route_url

    def unsubscribe_url(self, h_userid, tag):
        """Generate the url for `email.unsubscribe` with the right token."""
        token = self._generate_token(h_userid, tag)
        return self._route_url("email.unsubscribe", _query={"token": token})

    def unsubscribe(self, token):
        """Create a new entry in EmailUnsubscribe based on the email and tag encode in `token`."""
        data = self._decode_token(token)

        bulk_upsert(
            self._db,
            model_class=EmailUnsubscribe,
            values=[data],
            index_elements=["h_userid", "tag"],
            update_columns=["updated"],
        )

    def h_userid(self, url: str) -> str:
        """Return the decoded h_userid from the given URL.

        `url` should be a URL generated by one of this service's methods above.

        :raises UnrecognisedURLError: if the given URL does not appear to be
            one generated by this service
        :raises InvalidTokenError: if the URL's authentication token is invalid
            or has expired
        """
        try:
            token = parse_qs(urlparse(url).query)["token"][0]
        except (KeyError, ValueError) as err:
            raise UnrecognisedURLError() from err

        try:
            return self._decode_token(token)["h_userid"]
        except (ExpiredJWTError, InvalidJWTError) as err:
            raise InvalidTokenError() from err

    def _generate_token(self, h_userid, tag):
        return self._jwt_service.encode_with_secret(
            {"h_userid": h_userid, "tag": tag},
            self._secret,
            lifetime=timedelta(days=30),
        )

    def _decode_token(self, token):
        return self._jwt_service.decode_with_secret(token, self._secret)


def factory(_context, request):
    return EmailPreferencesService(
        request.db,
        request.find_service(iface=JWTService),
        secret=request.registry.settings["jwt_secret"],
        route_url=request.route_url,
    )
