"""Create table to store course rosters."""

import sqlalchemy as sa
from alembic import op

revision = "1b52e0668e7c"
down_revision = "3d0c022c716c"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_roster",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("authority_provided_id", sa.Unicode(), nullable=False),
        sa.Column("h_userid", sa.Unicode(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("lti_role_id", sa.Integer(), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lti_role_id"],
            ["lti_role.id"],
            name=op.f("fk__course_roster__lti_role_id__lti_role"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__course_roster")),
        sa.UniqueConstraint(
            "authority_provided_id",
            "h_userid",
            "lti_role_id",
            name=op.f("uq__course_roster__authority_provided_id"),
        ),
    )
    op.create_index(
        op.f("ix__course_roster_authority_provided_id"),
        "course_roster",
        ["authority_provided_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix__course_roster_h_userid"), "course_roster", ["h_userid"], unique=False
    )
    op.create_index(
        op.f("ix__course_roster_lti_role_id"),
        "course_roster",
        ["lti_role_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(op.f("ix__course_roster_lti_role_id"), table_name="course_roster")
    op.drop_index(op.f("ix__course_roster_h_userid"), table_name="course_roster")
    op.drop_index(op.f("ix__course_roster_h_course_id"), table_name="course_roster")
    op.drop_table("course_roster")
