"""
registration

Revision ID: 666f85ece91d
Revises: e22fa595b11d
Create Date: 2022-02-25 09:20:25.615907

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "666f85ece91d"
down_revision = "e22fa595b11d"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registration",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("issuer", sa.UnicodeText(), nullable=True),
        sa.Column("client_id", sa.UnicodeText(), nullable=True),
        sa.Column("key_set_url", sa.UnicodeText(), nullable=True),
        sa.Column("auth_login_url", sa.UnicodeText(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__registration")),
    )
    op.add_column(
        "application_instances",
        sa.Column("application_instance_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk__application_instances__application_instance_id__registration"),
        "application_instances",
        "registration",
        ["application_instance_id"],
        ["id"],
        ondelete="cascade",
    )
    op.drop_column("application_instances", "client_id")
    op.drop_column("application_instances", "issuer")
    op.drop_column("application_instances", "auth_login_url")
    op.drop_column("application_instances", "key_set_url")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application_instances",
        sa.Column("key_set_url", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "application_instances",
        sa.Column("auth_login_url", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "application_instances",
        sa.Column("issuer", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "application_instances",
        sa.Column("client_id", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        op.f("fk__application_instances__application_instance_id__registration"),
        "application_instances",
        type_="foreignkey",
    )
    op.drop_column("application_instances", "application_instance_id")
    op.drop_table("registration")
    # ### end Alembic commands ###
