"""
add_lti_1.1_constraint

Revision ID: 6ad682b6646f
Revises: e22fa595b11d
Create Date: 2022-02-11 11:18:58.313558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad682b6646f'
down_revision = 'e22fa595b11d'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
