"""
Create user table.

Revision ID: 7178f5812e85
Revises: d9c9e65c463e
Create Date: 2021-08-23 15:39:24.722566

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7178f5812e85"
down_revision = "d9c9e65c463e"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lti_user",
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UnicodeText(), nullable=False),
        sa.Column("oauth_consumer_key", sa.UnicodeText(), nullable=False),
        sa.Column("roles", sa.UnicodeText(), nullable=False),
        sa.Column("tool_consumer_instance_guid", sa.UnicodeText(), nullable=False),
        sa.Column("display_name", sa.UnicodeText(), nullable=True),
        sa.Column("email", sa.UnicodeText(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
