"""
rollup_users

Revision ID: 7c9bddc05490
Revises: f3d2cb377070
Create Date: 2022-10-06 14:19:11.213612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7c9bddc05490"
down_revision = "f3d2cb377070"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rollup_users_by_org",
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk__rollup_users_by_org__organization_id__organization"),
        ),
        sa.PrimaryKeyConstraint(
            "organization_id", "role", "timestamp", name=op.f("pk__rollup_users_by_org")
        ),
    )
    op.create_index(
        op.f("ix__rollup_users_by_org_timestamp"),
        "rollup_users_by_org",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rollup_organization_events",
        "organization_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_index(
        op.f("ix__rollup_users_by_org_timestamp"), table_name="rollup_users_by_org"
    )
    op.drop_table("rollup_users_by_org")
    # ### end Alembic commands ###
