"""
lti_roles_scope

Revision ID: 9e119d890206
Revises: 52755322151e
Create Date: 2022-11-11 18:46:41.936859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e119d890206'
down_revision = '52755322151e'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lti_role', sa.Column('scope', sa.Enum('course', 'institution', 'system', name='rolescope', native_enum=False, length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lti_role', 'scope')
    # ### end Alembic commands ###
