"""
empty message

Revision ID: 9ee0679761f0
Revises: c9b1542a714b
Create Date: 2021-06-24 15:43:47.561118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9ee0679761f0"
down_revision = "c9b1542a714b"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq__oauth2_token__user_id", "oauth2_token", type_="unique")
    op.create_unique_constraint(
        op.f("uq__oauth2_token__user_id"),
        "oauth2_token",
        ["user_id", "consumer_key", "api_host"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq__oauth2_token__user_id"), "oauth2_token", type_="unique"
    )
    op.create_unique_constraint(
        "uq__oauth2_token__user_id", "oauth2_token", ["user_id", "consumer_key"]
    )
    # ### end Alembic commands ###
