"""
empty message

Revision ID: c9b1542a714b
Revises: bf67a1e68cea
Create Date: 2021-06-24 14:18:24.324067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c9b1542a714b"
down_revision = "bf67a1e68cea"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("oauth2_token", sa.Column("api_host", sa.Unicode(), nullable=False))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oauth2_token", "api_host")
