"""
registration

Revision ID: c9ebaebb3eca
Revises: 666f85ece91d
Create Date: 2022-02-25 09:22:43.590664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ebaebb3eca'
down_revision = '666f85ece91d'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_instances', sa.Column('registration_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk__application_instances__application_instance_id__reg_00a3', 'application_instances', type_='foreignkey')
    op.create_foreign_key(op.f('fk__application_instances__registration_id__registration'), 'application_instances', 'registration', ['registration_id'], ['id'], ondelete='cascade')
    op.drop_column('application_instances', 'application_instance_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_instances', sa.Column('application_instance_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk__application_instances__registration_id__registration'), 'application_instances', type_='foreignkey')
    op.create_foreign_key('fk__application_instances__application_instance_id__reg_00a3', 'application_instances', 'registration', ['application_instance_id'], ['id'], ondelete='CASCADE')
    op.drop_column('application_instances', 'registration_id')
    # ### end Alembic commands ###
