"""
grouping_membership

Revision ID: e02622d4088b
Revises: 2fd66b9ab1a1
Create Date: 2021-11-09 16:49:09.098472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e02622d4088b"
down_revision = "2fd66b9ab1a1"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grouping_membership",
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("grouping_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grouping_id"],
            ["grouping.id"],
            name=op.f("fk__grouping_membership__grouping_id__grouping"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk__grouping_membership__user_id__user"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__grouping_membership")),
        sa.UniqueConstraint(
            "grouping_id", "user_id", name=op.f("uq__grouping_membership__grouping_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("grouping_membership")
    # ### end Alembic commands ###
