"""
rollup

Revision ID: f3d2cb377070
Revises: 52755322151e
Create Date: 2022-10-06 12:59:08.857987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d2cb377070'
down_revision = '52755322151e'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rollup_organization_events',
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_type.id'], name=op.f('fk__rollup_organization_events__event_type_id__event_type'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk__rollup_organization_events__organization_id__organization')),
    sa.PrimaryKeyConstraint('organization_id', 'event_type_id', 'timestamp', name=op.f('pk__rollup_organization_events'))
    )
    op.create_index(op.f('ix__rollup_organization_events_event_type_id'), 'rollup_organization_events', ['event_type_id'], unique=False)
    op.create_index(op.f('ix__rollup_organization_events_timestamp'), 'rollup_organization_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__rollup_organization_events_timestamp'), table_name='rollup_organization_events')
    op.drop_index(op.f('ix__rollup_organization_events_event_type_id'), table_name='rollup_organization_events')
    op.drop_table('rollup_organization_events')
    # ### end Alembic commands ###
