"""Add assignment document_uri column.

Revision ID: fa62e42cb531
Revises: 2a45f5cb8e25
"""

import sqlalchemy as sa
from alembic import op

revision = "fa62e42cb531"
down_revision = "2a45f5cb8e25"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assignment", sa.Column("document_uri", sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assignment", "document_uri")
    # ### end Alembic commands ###
