BDDtests:
  runs-on: ubuntu-latest
  services:
    postgres:
      image: postgres:11.5-alpine
      ports:
      - 5432:5432
  env:
    TEST_DATABASE_URL: postgresql://postgres@localhost:5432/lms_test
  steps:
    - uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg', 'tox.ini') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Create test database
      run: psql -U postgres -h localhost -p 5432 -c 'CREATE DATABASE lms_test'
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: python -m pip install tox
    - run: tox -e bddtests
