name: Continuous integration

on:
  pull_request:
    paths-ignore:
      - '.cookiecutter/*'
      - 'docs/*'
      - 'requirements/*.in'
      - 'requirements/dev.txt'
      - '**/.gitignore'
      - '*.md'
      - 'LICENSE'
  workflow_call:

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5-alpine
        ports:
        - 5433:5432
    env:
      TOX_PARALLEL_NO_SPINNER: 1

    steps:
    - name: Checkout git repo
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Install tox
      run: python -m pip install 'tox<4'

    - name: Create test databases
      run: |
        psql -U postgres -h localhost -p 5433 -c 'CREATE DATABASE lms_test'
        psql -U postgres -h localhost -p 5433 -c 'CREATE DATABASE lms_functests'
        psql -U postgres -h localhost -p 5433 -c 'CREATE DATABASE lms_bddtests'

    - name: Cache the .tox dir
      uses: actions/cache@v3
      with:
        path: .tox
        key: ${{ runner.os }}-tox-${{ hashFiles('tox.ini') }}-${{ hashFiles('requirements/*') }}-${{ hashFiles('setup.py') }}-${{ hashFiles('setup.cfg') }}
        restore-keys: |
          ${{ runner.os }}-tox-

    - name: Cache the node_modules dir
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}

    - name: yarn install
      run: yarn install --frozen-lockfile

    - name: yarn build
      run: yarn build

    - name: Run tox
      run: tox --parallel -e checkformatting,lint,tests,coverage,functests,bddtests

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache the node_modules dir
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}

    - name: Install
      run: yarn install --frozen-lockfile

    - name: Format
      run: yarn checkformatting

    - name: Lint
      run: yarn lint

    - name: Typecheck
      run: yarn typecheck

    - name: Test
      run: gulp test
